/**
 * Email Alert Sender
 * Sends alert notifications via email using SMTP.
 */

import type { Alert, EmailConfig, AlertDetails } from './types.ts';
import { makeLogger } from '../shared/log.ts';

const log = makeLogger('alert-email');

// ============================================================================
// Email Templates
// ============================================================================

const DEFAULT_SUBJECT_TEMPLATE = '[AgentZT Alert] {severity}: {title}';

const DEFAULT_BODY_TEMPLATE = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: #f5f5f5; padding: 15px; border-radius: 5px; margin-bottom: 20px; }
    .severity-critical { background: #dc3545; color: white; }
    .severity-error { background: #dc3545; color: white; }
    .severity-warning { background: #ffc107; color: #333; }
    .severity-info { background: #17a2b8; color: white; }
    .content { padding: 15px; background: #fff; border: 1px solid #ddd; border-radius: 5px; }
    .details { margin-top: 15px; padding: 10px; background: #f9f9f9; border-radius: 5px; }
    .detail-item { margin: 5px 0; }
    .label { font-weight: bold; }
    .footer { margin-top: 20px; padding: 10px; text-align: center; color: #666; font-size: 12px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header severity-{severity}">
      <h2>{title}</h2>
      <p>Alert Type: {type} | Severity: {severity}</p>
      <p>Time: {timestamp}</p>
    </div>
    <div class="content">
      <p>{message}</p>
    </div>
    {detailsSection}
    <div class="footer">
      <p>This alert was generated by AgentZT Gateway.</p>
      <p>Alert ID: {alertId}</p>
    </div>
  </div>
</body>
</html>
`;

// ============================================================================
// Email Sender Configuration
// ============================================================================

export interface EmailSenderConfig {
  /** SMTP host */
  host: string;
  /** SMTP port */
  port: number;
  /** Use secure connection (TLS) */
  secure: boolean;
  /** Authentication username */
  user: string;
  /** Authentication password */
  password: string;
  /** Sender email address */
  from: string;
  /** Sender name */
  fromName?: string;
}

// ============================================================================
// Email Sender Class
// ============================================================================

/**
 * Email alert sender using SMTP.
 * Note: This implementation uses Node.js built-in modules for basic SMTP support.
 * For production use, consider using nodemailer package.
 */
export class EmailAlertSender {
  private config: EmailSenderConfig;
  private enabled: boolean;

  constructor(config: EmailSenderConfig) {
    this.config = config;
    this.enabled = Boolean(config.host && config.user);
    if (!this.enabled) {
      log.warn('Email sender disabled: missing configuration');
    }
  }

  /**
   * Check if email sender is properly configured
   */
  isEnabled(): boolean {
    return this.enabled;
  }

  /**
   * Send an alert email
   */
  async sendAlert(alert: Alert, emailConfig: EmailConfig): Promise<boolean> {
    if (!this.enabled) {
      log.warn('Email sender disabled, skipping alert email');
      return false;
    }

    if (!emailConfig.recipients.length) {
      log.warn('No email recipients configured');
      return false;
    }

    try {
      const subject = this.renderTemplate(
        emailConfig.subjectTemplate ?? DEFAULT_SUBJECT_TEMPLATE,
        alert
      );

      const body = this.renderBodyTemplate(
        emailConfig.bodyTemplate ?? DEFAULT_BODY_TEMPLATE,
        alert,
        emailConfig.includeDetails
      );

      // Send email using SMTP
      await this.sendSmtpEmail(emailConfig.recipients, subject, body);

      log.info(`Alert email sent to ${emailConfig.recipients.length} recipients: ${alert.id}`);
      return true;
    } catch (error) {
      log.error(`Failed to send alert email: ${error}`);
      return false;
    }
  }

  /**
   * Send email via SMTP
   * This is a simplified implementation. For production, use nodemailer.
   */
  private async sendSmtpEmail(
    recipients: string[],
    subject: string,
    body: string
  ): Promise<void> {
    // Note: In production, use nodemailer package for reliable SMTP handling
    // This is a placeholder that logs the email for development/testing
    log.info(`[DEV MODE] Email would be sent:`);
    log.info(`  From: ${this.config.fromName ?? 'AgentZT'} <${this.config.from}>`);
    log.info(`  To: ${recipients.join(', ')}`);
    log.info(`  Subject: ${subject}`);
    log.info(`  Body length: ${body.length} characters`);

    // In production, uncomment and use nodemailer:
    // const nodemailer = await import('nodemailer');
    // const transporter = nodemailer.createTransport({
    //   host: this.config.host,
    //   port: this.config.port,
    //   secure: this.config.secure,
    //   auth: { user: this.config.user, pass: this.config.password },
    // });
    // await transporter.sendMail({
    //   from: `${this.config.fromName ?? 'AgentZT'} <${this.config.from}>`,
    //   to: recipients.join(','),
    //   subject,
    //   html: body,
    // });
  }

  /**
   * Render a template string with alert data
   */
  private renderTemplate(template: string, alert: Alert): string {
    return template
      .replace(/{title}/g, alert.title)
      .replace(/{message}/g, alert.message)
      .replace(/{severity}/g, alert.severity)
      .replace(/{type}/g, alert.type)
      .replace(/{timestamp}/g, alert.timestamp)
      .replace(/{alertId}/g, alert.id)
      .replace(/{appId}/g, alert.appId ?? 'N/A')
      .replace(/{userId}/g, alert.userId ?? 'N/A')
      .replace(/{agentId}/g, alert.agentId ?? 'N/A');
  }

  /**
   * Render the body template with optional details section
   */
  private renderBodyTemplate(
    template: string,
    alert: Alert,
    includeDetails: boolean
  ): string {
    let detailsSection = '';
    if (includeDetails) {
      detailsSection = this.renderDetailsSection(alert.details);
    }

    return this.renderTemplate(template, alert)
      .replace(/{detailsSection}/g, detailsSection);
  }

  /**
   * Render the details section HTML
   */
  private renderDetailsSection(details: AlertDetails): string {
    const items: string[] = [];

    if (details.riskLevel) {
      items.push(`<div class="detail-item"><span class="label">Risk Level:</span> ${details.riskLevel}</div>`);
    }
    if (details.categories && details.categories.length > 0) {
      items.push(`<div class="detail-item"><span class="label">Categories:</span> ${details.categories.join(', ')}</div>`);
    }
    if (details.score !== undefined) {
      items.push(`<div class="detail-item"><span class="label">Score:</span> ${details.score.toFixed(2)}</div>`);
    }
    if (details.quotaPercentage !== undefined) {
      items.push(`<div class="detail-item"><span class="label">Quota Usage:</span> ${details.quotaPercentage}%</div>`);
    }
    if (details.quotaType) {
      items.push(`<div class="detail-item"><span class="label">Quota Type:</span> ${details.quotaType}</div>`);
    }
    if (details.anomalyType) {
      items.push(`<div class="detail-item"><span class="label">Anomaly Type:</span> ${details.anomalyType}</div>`);
    }
    if (details.eventCount !== undefined) {
      items.push(`<div class="detail-item"><span class="label">Event Count:</span> ${details.eventCount}</div>`);
    }
    if (details.timeWindowSeconds !== undefined) {
      items.push(`<div class="detail-item"><span class="label">Time Window:</span> ${details.timeWindowSeconds}s</div>`);
    }

    // Add event data if present
    if (details.eventData) {
      items.push(`<div class="detail-item"><span class="label">Event Data:</span></div>`);
      items.push(`<pre style="background: #eee; padding: 10px; overflow-x: auto;">${JSON.stringify(details.eventData, null, 2)}</pre>`);
    }

    if (items.length === 0) {
      return '';
    }

    return `<div class="details">${items.join('\n')}</div>`;
  }
}

// ============================================================================
// Factory Function
// ============================================================================

let defaultEmailSender: EmailAlertSender | null = null;

/**
 * Get or create the default email sender
 */
export function getEmailSender(config?: EmailSenderConfig): EmailAlertSender {
  if (!defaultEmailSender && config) {
    defaultEmailSender = new EmailAlertSender(config);
  }
  if (!defaultEmailSender) {
    // Return a disabled sender if no config provided
    defaultEmailSender = new EmailAlertSender({
      host: '',
      port: 587,
      secure: false,
      user: '',
      password: '',
      from: 'alerts@agentzt.local',
    });
  }
  return defaultEmailSender;
}

/**
 * Reset the email sender (for testing)
 */
export function resetEmailSender(): void {
  defaultEmailSender = null;
}